import { StageName as PrismaStageName } from "@prisma/client"

/**
 * Stage names in execution order
 */
export const STAGE_ORDER: PrismaStageName[] = [
  "RESEARCH",
  "SCRIPT",
  "VOICE",
  "MUSIC",
  "VISUAL",
  "EDITOR",
  "PUBLISH",
]

/**
 * Base interface for all stage handlers
 */
export interface StageHandler {
  /** Stage name this handler processes */
  name: PrismaStageName

  /** Validate input before execution */
  validate(input: unknown): ValidationResult

  /** Execute the stage logic */
  execute(context: StageContext): Promise<StageResult>
}

/**
 * Validation result
 */
export interface ValidationResult {
  valid: boolean
  errors?: string[]
}

/**
 * Context provided to stage execution
 */
export interface StageContext {
  pipelineId: string
  stageId: string
  input: StageInput
  previousOutput?: unknown
  config?: StageConfig
}

/**
 * Generic stage input
 */
export interface StageInput {
  topic?: string
  description?: string
  [key: string]: unknown
}

/**
 * Stage configuration options
 */
export interface StageConfig {
  timeout?: number
  retries?: number
  [key: string]: unknown
}

/**
 * Result of stage execution
 */
export interface StageResult {
  success: boolean
  output: unknown
  artifacts?: Artifact[]
  error?: string
  metadata?: Record<string, unknown>
}

/**
 * Artifact generated by a stage
 */
export interface Artifact {
  url: string
  type: "audio" | "video" | "image" | "json" | "text"
  name: string
  size?: number
}

// ============================================
// Stage-specific output types
// ============================================

/**
 * Research stage output
 */
export interface ResearchOutput {
  topic: string
  facts: string[]
  sources: Source[]
  hooks: string[]
  targetAudience: string
  estimatedDuration: number
}

export interface Source {
  title: string
  url: string
  snippet: string
}

/**
 * Script stage output
 */
export interface ScriptOutput {
  hook: string
  body: ScriptSection[]
  cta: string
  fullScript: string
  estimatedDuration: number
  speakerNotes: string[]
}

export interface ScriptSection {
  heading: string
  content: string
  visualCue: string
  duration: number
}

/**
 * Voice stage output
 */
export interface VoiceOutput {
  audioUrl: string
  duration: number
  timestamps?: Timestamp[]
  transcript: string
}

export interface Timestamp {
  word: string
  start: number
  end: number
}

/**
 * Music stage output
 */
export interface MusicOutput {
  audioUrl: string
  duration: number
  bpm?: number
  genre?: string
  source: string
}

/**
 * Visual stage output
 */
export interface VisualOutput {
  clips: VideoClip[]
  images: ImageAsset[]
  overlays: Overlay[]
}

export interface VideoClip {
  url: string
  duration: number
  startTime: number
  description: string
  source: string
}

export interface ImageAsset {
  url: string
  description: string
  useAt: number
  duration: number
}

export interface Overlay {
  type: "text" | "graphic" | "caption"
  content: string
  startTime: number
  duration: number
  style?: Record<string, unknown>
}

/**
 * Editor stage output
 */
export interface EditorOutput {
  videoUrl: string
  duration: number
  thumbnailUrl: string
  format: VideoFormat
  renderTime: number
}

export interface VideoFormat {
  width: number
  height: number
  fps: number
  codec?: string
}

/**
 * Publish stage output
 */
export interface PublishOutput {
  platforms: PlatformResult[]
  publishedAt: string
}

export interface PlatformResult {
  platform: string
  url: string
  postId: string
  success: boolean
  error?: string
}

// ============================================
// Stage weights for attribution
// ============================================

export const STAGE_WEIGHTS: Record<PrismaStageName, number> = {
  RESEARCH: 10,
  SCRIPT: 25,
  VOICE: 20,
  MUSIC: 10,
  VISUAL: 15,
  EDITOR: 15,
  PUBLISH: 5,
}
